# Numpy Arrays and Pandas basics:

In [5]:
print('Nida Mirza\n180630107030')
import numpy as np
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

np_height = np.array(height)
np_weight = np.array(weight)
print(np_height)
print(np_weight)

Nida Mirza
180630107030
[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]


In [7]:
print('Nida Mirza\n180630107030')
a=np.array([(1,2,3),(4,5,6)])
print(a)

Nida Mirza
180630107030
[[1 2 3]
 [4 5 6]]


In [8]:
print('Nida Mirza\n180630107030')
import time
import sys
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print((time.time()-start)*1000)

Nida Mirza
180630107030
280.64632415771484
446.8393325805664


# Pandas Basics

In [9]:
print('Nida Mirza\n180630107030')

dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

Nida Mirza
180630107030
        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


In [10]:
print('Nida Mirza\n180630107030')
brics.index = ["BR", "RU", "IN", "CH", "SA"]
print(brics)

Nida Mirza
180630107030
         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98
